name: GitHub Actions Demo Day 1

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
   branches: [main]
  schedule:
   - cron: '15 * * 6 1'
  workflow_dispatch:
   
   
   
 
